version: '3'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://zanews@db/zanews
      - DJANGO_DEBUG=True
      - NODE_ENV=development
      - DJANGO_DEBUG_TOOLBAR=${DJANGO_DEBUG_TOOLBAR}
      - DJANGO_SECRET_KEY=not-secret-in-dev
      - DJANGO_WHITENOISE_AUTOREFRESH=True
      - TAG_MANAGER_ENABLED=False

  db:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=zanews
      - POSTGRES_DB=zanews
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
