# Generated by Django 2.2.9 on 2020-01-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_publication_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="url", new_name="published_url",
        ),
    ]
