# Generated by Django 2.2.9 on 2020-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200202_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
