# Generated by Django 2.2.9 on 2020-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200202_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
