# Generated by Django 2.2.9 on 2020-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200202_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_url',
            field=models.TextField(unique=True),
        ),
    ]
