# Generated by Django 2.2.9 on 2020-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200202_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_html',
            field=models.TextField(blank=True, help_text='The raw original HTML. Kept to be able to re-extract plain text if needed', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='spider_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
