# Generated by Django 2.2.9 on 2020-02-05 19:44

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200202_1922'),
    ]

    migration = '''
        CREATE TRIGGER content_search_update BEFORE INSERT OR UPDATE
        ON articles_article FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(
            full_text_search, 'pg_catalog.english',
            title, body_text
         );

        -- Force triggers to run and populate the text_search column.
        UPDATE articles_article set ID = ID;
    '''

    reverse_migration = '''
        DROP TRIGGER full_text_search ON articles_article;
    '''

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_text_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RunSQL(migration, reverse_migration)
    ]
