# Generated by Django 2.2.9 on 2020-02-05 20:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_full_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_text_search'], name='articles_ar_full_te_4c6be2_gin'),
        ),
    ]
